wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
batch_size:
  desc: null
  value: 64
channel_1_neurons:
  desc: null
  value: 20
channel_2_neurons:
  desc: null
  value: 20
epochs:
  desc: null
  value: 750
lr:
  desc: null
  value: 0.0003
