wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_size:
  desc: null
  value: 32
decay:
  desc: null
  value: 0
dropout_1:
  desc: null
  value: 'No'
dropout_2:
  desc: null
  value: 'No'
epochs:
  desc: null
  value: 200
hidden_layer_1:
  desc: null
  value: 15
hidden_layer_2:
  desc: null
  value: 10
layers:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.0003
